no longer using config inside of the file, now using options for the command. removed config mode.

diff --git a/fancygrim b/fancygrim
--- a/fancygrim
+++ b/fancygrim
@@ -3,28 +3,30 @@
 # fancygrim for hyprland (nvidia)
 # features:
 #  - read README.md on git repo (https://github.com/memyboi/fancygrim)
-
-#  ____ ___  _   _ _____ ___ ____
-# / ___/ _ \| \ | |  ___|_ _/ ___|
-#| |  | | | |  \| | |_   | | |  _
-#| |__| |_| | |\  |  _|  | | |_| |
-# \____\___/|_| \_|_|   |___\____|
-AREA_SHADOW=true # toggle shadow for "area" screenshots
-AREA_CORNER_INTENSITY=15 # border radius for "area" screenshots, 0 for disable
-WINDOW_SHADOW=true # toggle shadow for "window" screenshots
-WINDOW_CORNER_INTENSITY=15 # border radius for "window" screenshots, 0 for disable
-FULL_SHADOW=false # toggle shadow for "full" screenshots
-FULL_CORNER_INTENSITY=0 # border radius for "full" screenshots, 0 for disable
-SEND_NOTIF=true # toggle notification, useful for people without a notification daemon.
-SEND_PRE_NOTIF=true # toggle waiting notification.
-NOTIF_IMAGE=true # toggle image in notification
-COPY_TO_CLIPBOARD=true # toggle whether /tmp/fancygrimss.png should be saved to the clipboard.
-PASTE_ONCE=false # toggle whether paste once or not
+#  - im too lazy to rewrite them here ;-;
 
 
 
 
 
+
+
+
+
+
+
+
+
+
+
+# RUNTIME
+SHADOW=false
+CORNER=10
+NOTIF=true
+PRENOTIF=true
+COPY=true
+ONEPASTE=false
+NOTIFIMAGE=true
 
 
 
@@ -37,7 +39,7 @@ PASTE_ONCE=false # toggle whether paste once or not
 # DO NOT MODIFY THE FOLLOWING UNLESS YOU KNOW WHAT YOU'RE DOING
 usage() {
   echo "Usage:"
-  echo "  fancygrim (area|window|full|config)"
+  echo "  fancygrim (area|window|full) [--corner (N) | -c (N)] [--shadow | -s] [--silence | -d] [--pasteonce | -o] [--nocopy | -n] [--noimage -i]"
   echo "  fancygrim usage"
   echo ""
   echo "  area:"
@@ -61,9 +63,9 @@ addcorners() {
 }
 
 copytoclipboard() {
-  if [ $COPY_TO_CLIPBOARD = true ]; then
+  if [ $COPY = true ]; then
     ONCE=""
-    if [ $PASTE_ONCE = true ]; then
+    if [ $ONEPASTE = true ]; then
       ONCE="-o"
     fi
     wl-copy $ONCE < /tmp/fancygrimss.png
@@ -71,13 +73,13 @@ copytoclipboard() {
 }
 
 sendnotif() {
-  if [ $SEND_NOTIF = true ]; then
+  if [ $NOTIF = true ]; then
     IMAGE=""
     CLIPBOARD="screenshot saved to /tmp/fancygrimss.png."
-    if [ $NOTIF_IMAGE = true ]; then
+    if [ $NOTIFIMAGE = true ]; then
       IMAGE='-i /tmp/fancygrimss.png'
     fi
-    if [ $COPY_TO_CLIPBOARD = true ]; then
+    if [ $COPY = true ]; then
       CLIPBOARD='screenshot copied to clipboard.'
     fi
     notify-send -t 2000 "Screenshot taken" "$1 $CLIPBOARD" $IMAGE
@@ -97,10 +99,10 @@ area() {
   kill "$hyprpicker_pid"
   prenotif
   convert /tmp/fancygrimss.png -crop $RES /tmp/fancygrimss.png
-  if [ $AREA_CORNER_INTENSITY -gt 0 ]; then 
-    addcorners "${RAWSIZE[0]}" "${RAWSIZE[1]}" "$AREA_CORNER_INTENSITY"
+  if [ $CORNER -gt 0 ]; then 
+    addcorners "${RAWSIZE[0]}" "${RAWSIZE[1]}" "$CORNER"
   fi
-  if [ $AREA_SHADOW = true ]; then
+  if [ $SHADOW = true ]; then
     addshadow
   fi
   copytoclipboard
@@ -114,13 +116,17 @@ window() { # touch up later, is a little slow.
   IFS=' ' read -ra SPLITRAWRES <<< "$RAWRES"
   IFS=',' read -ra RAWPOS <<< "${SPLITRAWRES[0]}"
   IFS='x' read -ra RAWSIZE <<< "${SPLITRAWRES[1]}"
-  RES=${RAWSIZE[0]}x${RAWSIZE[1]}+${RAWPOS[0]}+${RAWPOS[1]}
+  POSX=${RAWPOS[0]}
+  POSY=${RAWPOS[1]}
+  SIZX=${RAWSIZE[0]}
+  SIZY=${RAWSIZE[1]}
+  RES=${SIZX}x${SIZY}+${POSX}+${POSY}
 
   convert /tmp/fancygrimss.png -crop $RES /tmp/fancygrimss.png
-  if [ $WINDOW_CORNER_INTENSITY -gt 0 ]; then
-    addcorners "${RAWSIZE[0]}" "${RAWSIZE[1]}" "$WINDOW_CORNER_INTENSITY"
+  if [ $CORNER -gt 0 ]; then
+    addcorners "${SIZX}" "${SIZY}" "$CORNER"
   fi
-  if [ $WINDOW_SHADOW = true ]; then
+  if [ $SHADOW = true ]; then
     addshadow
   fi
   copytoclipboard
@@ -130,13 +136,13 @@ window() { # touch up later, is a little slow.
 full() {
   grim "/tmp/fancygrimss.png"
   prenotif
-  if [ $FULL_CORNER_INTENSITY -gt 0 ]; then
+  if [ $CORNER -gt 0 ]; then
     SIZE=$(convert /tmp/fancygrimss.png -print "%w %h" /dev/null)
     WIDTH=$(echo $SIZE | cut -d ' ' -f 1)
     HEIGHT=$(echo $SIZE | cut -d ' ' -f 2)
-    addcorners "$WIDTH" "$HEIGHT" "$FULL_CORNER_INTENSITY"
+    addcorners "$WIDTH" "$HEIGHT" "$CORNER"
   fi
-  if [ $FULL_SHADOW = true ]; then
+  if [ $SHADOW = true ]; then
     addshadow
   fi
   copytoclipboard
@@ -144,19 +150,62 @@ full() {
 }
 
 prenotif() {
-  if [ $SEND_PRE_NOTIF = true ]; then
+  if [ $NOTIF = true ]; then
     notify-send -t 2000 "Taking screenshot..." "Please wait.. (You can do other things while you wait.)"
     # just cuz processing takes a while
   fi
 }
 
-config() {
-  nano $0 # Opens arg 0 (file) in nano
-  # any sensible shell should recognise $0 as "/usr/bin/fancygrim" and not "fancygrim"
-}
+MODE=$1
+
+while [ $# -gt 0 ]; do
+  key="$2"
+  case $key in
+    -d | --silence)
+      NOTIF=false
+      PRENOTIF=false
+      NOTIFIMAGE=false
+      shift
+      ;;
+
+    -o | --pasteonce)
+      ONEPASTE=true
+      shift
+      ;;
+    
+    -s | --shadow)
+      SHADOW=true
+      shift
+      ;;
+
+    -i | --noimage)
+      NOTIFIMAGE=false
+      shift
+      ;;
+
+    -c | --corner)
+      shift
+      if [ $# -gt 0 ]; then
+        CORNER="$2"
+        shift
+      else
+        echo "Error: Missing argument for $1 option."
+        exit 1
+      fi
+      ;;
+    -n | --nocopy)
+      COPY=false
+      shift
+      ;;
+
+    *)
+      break
+      ;;
+
+  esac
+done
 
 # Args handler
-MODE=$1
 if [ "$MODE" = "area" ]; then
   area
 elif [ "$MODE" = "window" ]; then
@@ -165,8 +214,6 @@ elif [ "$MODE" = "full" ]; then
   full
 elif [ "$MODE" = "usage" ]; then
   usage
-elif [ "$MODE" = "config" ]; then
-  config
 else
   echo "No action supplied."
   usage
